name: Deploy Frontend & Backend

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-1
      S3_BUCKET_NAME: aws-react-goalproject-expense-tracker-app
      LAMBDA_FUNCTION_NAME: addExpense

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 🚀 Frontend
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build Frontend
      working-directory: expense-tracker
      run: |
        npm install
        npm run build

    - name: Deploy Frontend to S3
      run: |
        aws s3 sync expense-tracker/build s3://${{ env.S3_BUCKET_NAME }} --delete

    # 🐍 Backend
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Build backend package (deps + code)
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t .
        zip -r ../function.zip .

    - name: Deploy Backend to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://expense-tracker-backend.zip
