name: Deploy Frontend & Backend

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build frontend
        run: |
          cd expense-tracker
          npm install
          npm run build

      - name: Sync frontend to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: aws-react-goalproject-expense-tracker-app
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1
          SOURCE_DIR: expense-tracker/build

      - name: Zip backend lambda function
        run: |
          cd expense-tracker-backend
          zip -r ../expense-tracker-backend.zip .

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name addExpense \
            --zip-file fileb://expense-tracker-backend.zip \
            --region ap-southeast-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1
